imports:
    - { resource: parameters.yml }

# Put parameters here that don't need to change on each machine where the app is deployed
# http://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: en

framework:
    secret:          "%secret%"
    validation:      { enable_annotations: true }
    default_locale:  "%locale%"

csv_objects:
    classes:
        result-via-config:     'CSVObjects\CSVObjectsBundle\Tests\Objects\Result'
        schoolName-via-config: ['CSVObjects\CSVObjectsBundle\Tests\Objects\SchoolRepository', 'findSchoolByName']
        studentId-via-config:  ['CSVObjects\CSVObjectsBundle\Tests\Objects\StudentRepository', 'findStudentById' ]
